name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker Image
        run: docker build -t health-metrics .

      - name: Push Docker Image to Azure Container Registry
        env:
          AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        run: |
          az acr login --name <your-registry-name>
          docker tag health-metrics <your-registry-name>.azurecr.io/health-metrics:latest
          docker push <your-registry-name>.azurecr.io/health-metrics:latest

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: <your-app-name>
          slot-name: production
          images: <your-registry-name>.azurecr.io/health-metrics:latest
